// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk4fHf-UWEI3EAM2_Oa4USqP93OsJu3kQ',
    appId: '1:541911883290:web:3418316cfa8bd34c2e7ba3',
    messagingSenderId: '541911883290',
    projectId: 'medi-c69c5',
    authDomain: 'medi-c69c5.firebaseapp.com',
    storageBucket: 'medi-c69c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWFO1czNUsQ6TW8gDKz20qRxLStqohDs8',
    appId: '1:541911883290:android:4d85ef00599e14802e7ba3',
    messagingSenderId: '541911883290',
    projectId: 'medi-c69c5',
    storageBucket: 'medi-c69c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXeH70Lct5vIjEAyvUsFPZa2D6VnLdfQs',
    appId: '1:541911883290:ios:8668b9a2ed2dc1f92e7ba3',
    messagingSenderId: '541911883290',
    projectId: 'medi-c69c5',
    storageBucket: 'medi-c69c5.appspot.com',
    iosClientId: '541911883290-059lsvk8h9ff0prmq7c2qhq7unka7jdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXeH70Lct5vIjEAyvUsFPZa2D6VnLdfQs',
    appId: '1:541911883290:ios:1d0a24520fb8585d2e7ba3',
    messagingSenderId: '541911883290',
    projectId: 'medi-c69c5',
    storageBucket: 'medi-c69c5.appspot.com',
    iosClientId: '541911883290-co2jo93ebpdbbdsgct75k4f2m06381f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainPro.RunnerTests',
  );
}
